  spark-master:
    image: pfk-spark-final5
    command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
    hostname: spark-master
    environment:
      MASTER: spark://spark-master:7077
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 192.168.0.7
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/spark-master:/conf
      - ./data:/tmp/data  
  

  spark-worker-1:
    image: pfk-spark-final5
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-1
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 192.168.0.7
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    links:
      - spark-master
      - ocr-1
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/spark-worker-1:/conf
      - ./data:/var2    

  spark-worker-2:
    image: pfk-spark-final5
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    hostname: spark-worker-2
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_PUBLIC_DNS: 192.168.0.7
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2g
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
    links:
      - spark-master
      - ocr-2
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8882
    ports:
      - 8082:8082
    volumes:
      - ./conf/spark-worker-2:/conf
      - ./data:/var2

  ocr-1:  
    hostname: ocr-1  
    image:  pourfard/ocr:0.0.2
    entrypoint: python3 main.py
    ports: 
      - 8086:9191 

  ocr-2:  
    hostname: ocr-2  
    image:  pourfard/ocr:0.0.2
    entrypoint: python3 main.py
    ports: 
      - 8087:9191
